# permissions for end users to view hstreamdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hstreamdb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hstream-operator
    app.kubernetes.io/part-of: hstream-operator
    app.kubernetes.io/managed-by: kustomize
  name: hstreamdb-viewer-role
rules:
- apiGroups:
  - apps.hstream.io
  resources:
  - hstreamdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.hstream.io
  resources:
  - hstreamdbs/status
  verbs:
  - get
